---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.130.0.6
  tasks:
    - name: Change mongo config file
      become : true
      template:
        src : templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tags
      notify: restart mongod

    - name: APT Install
      become : true
      apt:
        name: git
        state: present
        update_cache: yes
      tags: deploy-tag

    - name: Add unit file for Puma
      become : true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
        mode: 0644
      tags: app-tag
      notify: reload puma

    - name: Add config for DB connection
      become : true
      template:
        src : templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu
        mode: 0644
      tags: app-tag

    - name: enable puma
      become : true
      systemd: name=puma enabled=yes
      tags: app-tag

    - name: Fetch the latest version of application code
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      tags: deploy-tag

  handlers:
  - name: restart mongod
    become : true
    service: name=mongod state=restarted
  - name: reload puma
    become : true
    service: name=puma state=restarted
