---
- name: Configure MongoDB
  hosts: db
  become : true
  tags: db-tag
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src : templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

- name: Configure app
  hosts: app
  become : true
  tags: app-tag
  vars:
   db_host: 10.130.0.33
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
        mode: 0644
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted

- name: deploy application
  hosts: app
  tags: deploy-tag
  tasks:
    - name: APT Install
      become : true
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Fetch the latest version of application code
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
  - name: reload puma
    become : true
    systemd: name=puma state=restarted
